import 'module_file.dart';
import 'module_integration.dart';
import 'module_option.dart';
import 'module_requirements.dart';

/// Defines the complete configuration and metadata of an FKIT module.
class ModuleDefinition {
  /// Creates a module definition.
  const ModuleDefinition({
    required this.name,
    required this.displayName,
    required this.description,
    required this.version,
    required this.files,
    required this.requirements,
    required this.options,
    required this.integration,
  });

  /// The unique name of the module.
  final String name;

  /// The human-readable name of the module.
  final String displayName;

  /// A description of the module and its purpose.
  final String description;

  /// The version of the module.
  final String version;

  /// The files generated by the module.
  final List<ModuleFile> files;

  /// The package and code-generation requirements of the module.
  final ModuleRequirements requirements;

  /// The configurable options supported by the module.
  final Map<String, ModuleOption> options;

  /// The project integration configuration of the module.
  final ModuleIntegration integration;

  /// Creates a module definition from the provided [map].
  factory ModuleDefinition.fromMap(Map<dynamic, dynamic> map) {
    final optionsMap = Map<dynamic, dynamic>.from(map['options'] ?? const {});

    return ModuleDefinition(
      name: map['name'].toString(),
      displayName: map['display_name'].toString(),
      description: map['description'].toString(),
      version: map['version'].toString(),
      files: (map['files'] as List)
          .map(
            (e) => ModuleFile.fromMap(
              Map<dynamic, dynamic>.from(e),
            ),
          )
          .toList(),
      requirements: ModuleRequirements.fromMap(
        Map<dynamic, dynamic>.from(map['requires'] ?? const {}),
      ),
      options: optionsMap.map(
        (key, value) => MapEntry(
          key.toString(),
          ModuleOption.fromMap(
            name: key.toString(),
            map: Map<dynamic, dynamic>.from(value),
          ),
        ),
      ),
      integration: ModuleIntegration.fromMap(
        Map<dynamic, dynamic>.from(map['integration'] ?? const {}),
      ),
    );
  }

  /// Whether the module requires build runner execution.
  bool get requiresBuildRunner => requirements.buildRunner;

  /// Whether the module requires Flutter code generation.
  bool get requiresFlutterGen => requirements.flutterGen;

  /// Whether the module defines runtime package dependencies.
  bool get hasPackages => requirements.packages.isNotEmpty;

  /// Whether the module defines development package dependencies.
  bool get hasDevPackages => requirements.devPackages.isNotEmpty;

  /// Whether the module provides configurable options.
  bool get hasOptions => options.isNotEmpty;

  /// Whether the module requires project integration.
  bool get requiresIntegration => integration.enabled;
}
