/// Defines a file generated by an FKIT module.
class ModuleFile {
  /// The path to the source template file.
  final String template;

  /// The output path where the generated file is written.
  final String output;

  /// The optional module option controlling whether this file is generated.
  final String? when;

  /// Creates a module file configuration.
  const ModuleFile({
    required this.template,
    required this.output,
    this.when,
  });

  /// Creates a module file configuration from the provided [map].
  factory ModuleFile.fromMap(Map<dynamic, dynamic> map) {
    return ModuleFile(
      template: map['template'].toString(),
      output: map['output'].toString(),
      when: map['when']?.toString(),
    );
  }

  /// Whether the file is generated conditionally.
  bool get isConditional => when != null && when!.isNotEmpty;
}
